trigger:
  branches:
    include:
      - main

pool:
  name: LocalSelfHostedPool

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Install Node.js 22'

  - script: |
      npm install
      npm run build
    displayName: 'npm install & build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
    displayName: 'Publish artifact'
